# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 00:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('email', models.EmailField(max_length=200, verbose_name='E-mail')),
                ('department', models.CharField(max_length=100, verbose_name='Department')),
            ],
        ),
    ]
